
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T

interface _GlobalComponents {
  CategoryFilter: typeof import("../../components/CategoryFilter.vue")['default']
  Header: typeof import("../../components/Header.vue")['default']
  PriceDisplay: typeof import("../../components/PriceDisplay.vue")['default']
  SkillCard: typeof import("../../components/SkillCard.vue")['default']
  SkillList: typeof import("../../components/SkillList.vue")['default']
  NuxtWelcome: typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']
  NuxtLayout: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
  NuxtErrorBoundary: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
  ClientOnly: typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']
  DevOnly: typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']
  ServerPlaceholder: typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
  NuxtLink: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']
  NuxtLoadingIndicator: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
  NuxtTime: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
  NuxtRouteAnnouncer: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
  NuxtImg: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
  NuxtPicture: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
  VanActionBarButton: typeof import("../../node_modules/vant/es/action-bar-button/ActionBarButton")['default']
  VanAddressEdit: typeof import("../../node_modules/vant/es/address-edit/AddressEdit")['default']
  VanActionBar: typeof import("../../node_modules/vant/es/action-bar/ActionBar")['default']
  VanActionSheet: typeof import("../../node_modules/vant/es/action-sheet/ActionSheet")['default']
  VanArea: typeof import("../../node_modules/vant/es/area/Area")['default']
  VanAddressList: typeof import("../../node_modules/vant/es/address-list/AddressList")['default']
  VanBackTop: typeof import("../../node_modules/vant/es/back-top/BackTop")['default']
  VanActionBarIcon: typeof import("../../node_modules/vant/es/action-bar-icon/ActionBarIcon")['default']
  VanBadge: typeof import("../../node_modules/vant/es/badge/Badge")['default']
  VanBarrage: typeof import("../../node_modules/vant/es/barrage/Barrage")['default']
  VanButton: typeof import("../../node_modules/vant/es/button/Button")['default']
  VanCalendar: typeof import("../../node_modules/vant/es/calendar/Calendar")['default']
  VanCascader: typeof import("../../node_modules/vant/es/cascader/Cascader")['default']
  VanCard: typeof import("../../node_modules/vant/es/card/Card")['default']
  VanCellGroup: typeof import("../../node_modules/vant/es/cell-group/CellGroup")['default']
  VanCell: typeof import("../../node_modules/vant/es/cell/Cell")['default']
  VanCheckboxGroup: typeof import("../../node_modules/vant/es/checkbox-group/CheckboxGroup")['default']
  VanCheckbox: typeof import("../../node_modules/vant/es/checkbox/Checkbox")['default']
  VanCollapse: typeof import("../../node_modules/vant/es/collapse/Collapse")['default']
  VanCircle: typeof import("../../node_modules/vant/es/circle/Circle")['default']
  VanCol: typeof import("../../node_modules/vant/es/col/Col")['default']
  VanCollapseItem: typeof import("../../node_modules/vant/es/collapse-item/CollapseItem")['default']
  VanConfigProvider: typeof import("../../node_modules/vant/es/config-provider/ConfigProvider")['default']
  VanContactList: typeof import("../../node_modules/vant/es/contact-list/ContactList")['default']
  VanContactEdit: typeof import("../../node_modules/vant/es/contact-edit/ContactEdit")['default']
  VanContactCard: typeof import("../../node_modules/vant/es/contact-card/ContactCard")['default']
  VanCoupon: typeof import("../../node_modules/vant/es/coupon/Coupon")['default']
  VanCountDown: typeof import("../../node_modules/vant/es/count-down/CountDown")['default']
  VanDatePicker: typeof import("../../node_modules/vant/es/date-picker/DatePicker")['default']
  VanCouponList: typeof import("../../node_modules/vant/es/coupon-list/CouponList")['default']
  VanDropdownItem: typeof import("../../node_modules/vant/es/dropdown-item/DropdownItem")['default']
  VanCouponCell: typeof import("../../node_modules/vant/es/coupon-cell/CouponCell")['default']
  VanDivider: typeof import("../../node_modules/vant/es/divider/Divider")['default']
  VanDialog: typeof import("../../node_modules/vant/es/dialog/Dialog")['default']
  VanDropdownMenu: typeof import("../../node_modules/vant/es/dropdown-menu/DropdownMenu")['default']
  VanEmpty: typeof import("../../node_modules/vant/es/empty/Empty")['default']
  VanForm: typeof import("../../node_modules/vant/es/form/Form")['default']
  VanFloatingPanel: typeof import("../../node_modules/vant/es/floating-panel/FloatingPanel")['default']
  VanField: typeof import("../../node_modules/vant/es/field/Field")['default']
  VanIcon: typeof import("../../node_modules/vant/es/icon/Icon")['default']
  VanFloatingBubble: typeof import("../../node_modules/vant/es/floating-bubble/FloatingBubble")['default']
  VanHighlight: typeof import("../../node_modules/vant/es/highlight/Highlight")['default']
  VanGridItem: typeof import("../../node_modules/vant/es/grid-item/GridItem")['default']
  VanIndexAnchor: typeof import("../../node_modules/vant/es/index-anchor/IndexAnchor")['default']
  VanImage: typeof import("../../node_modules/vant/es/image/Image")['default']
  VanImagePreview: typeof import("../../node_modules/vant/es/image-preview/ImagePreview")['default']
  VanGrid: typeof import("../../node_modules/vant/es/grid/Grid")['default']
  VanLoading: typeof import("../../node_modules/vant/es/loading/Loading")['default']
  VanNavBar: typeof import("../../node_modules/vant/es/nav-bar/NavBar")['default']
  VanIndexBar: typeof import("../../node_modules/vant/es/index-bar/IndexBar")['default']
  VanNotify: typeof import("../../node_modules/vant/es/notify/Notify")['default']
  VanOverlay: typeof import("../../node_modules/vant/es/overlay/Overlay")['default']
  VanList: typeof import("../../node_modules/vant/es/list/List")['default']
  VanNoticeBar: typeof import("../../node_modules/vant/es/notice-bar/NoticeBar")['default']
  VanNumberKeyboard: typeof import("../../node_modules/vant/es/number-keyboard/NumberKeyboard")['default']
  VanPasswordInput: typeof import("../../node_modules/vant/es/password-input/PasswordInput")['default']
  VanPagination: typeof import("../../node_modules/vant/es/pagination/Pagination")['default']
  VanPickerGroup: typeof import("../../node_modules/vant/es/picker-group/PickerGroup")['default']
  VanProgress: typeof import("../../node_modules/vant/es/progress/Progress")['default']
  VanRadio: typeof import("../../node_modules/vant/es/radio/Radio")['default']
  VanPopup: typeof import("../../node_modules/vant/es/popup/Popup")['default']
  VanPicker: typeof import("../../node_modules/vant/es/picker/Picker")['default']
  VanRadioGroup: typeof import("../../node_modules/vant/es/radio-group/RadioGroup")['default']
  VanPopover: typeof import("../../node_modules/vant/es/popover/Popover")['default']
  VanPullRefresh: typeof import("../../node_modules/vant/es/pull-refresh/PullRefresh")['default']
  VanRate: typeof import("../../node_modules/vant/es/rate/Rate")['default']
  VanShareSheet: typeof import("../../node_modules/vant/es/share-sheet/ShareSheet")['default']
  VanRollingText: typeof import("../../node_modules/vant/es/rolling-text/RollingText")['default']
  VanSearch: typeof import("../../node_modules/vant/es/search/Search")['default']
  VanRow: typeof import("../../node_modules/vant/es/row/Row")['default']
  VanSignature: typeof import("../../node_modules/vant/es/signature/Signature")['default']
  VanSidebar: typeof import("../../node_modules/vant/es/sidebar/Sidebar")['default']
  VanSkeleton: typeof import("../../node_modules/vant/es/skeleton/Skeleton")['default']
  VanSkeletonAvatar: typeof import("../../node_modules/vant/es/skeleton-avatar/SkeletonAvatar")['default']
  VanSkeletonImage: typeof import("../../node_modules/vant/es/skeleton-image/SkeletonImage")['default']
  VanSkeletonParagraph: typeof import("../../node_modules/vant/es/skeleton-paragraph/SkeletonParagraph")['default']
  VanSkeletonTitle: typeof import("../../node_modules/vant/es/skeleton-title/SkeletonTitle")['default']
  VanSlider: typeof import("../../node_modules/vant/es/slider/Slider")['default']
  VanSidebarItem: typeof import("../../node_modules/vant/es/sidebar-item/SidebarItem")['default']
  VanSticky: typeof import("../../node_modules/vant/es/sticky/Sticky")['default']
  VanSpace: typeof import("../../node_modules/vant/es/space/Space")['default']
  VanStep: typeof import("../../node_modules/vant/es/step/Step")['default']
  VanStepper: typeof import("../../node_modules/vant/es/stepper/Stepper")['default']
  VanSwipe: typeof import("../../node_modules/vant/es/swipe/Swipe")['default']
  VanSubmitBar: typeof import("../../node_modules/vant/es/submit-bar/SubmitBar")['default']
  VanSwitch: typeof import("../../node_modules/vant/es/switch/Switch")['default']
  VanSwipeItem: typeof import("../../node_modules/vant/es/swipe-item/SwipeItem")['default']
  VanSwipeCell: typeof import("../../node_modules/vant/es/swipe-cell/SwipeCell")['default']
  VanTabs: typeof import("../../node_modules/vant/es/tabs/Tabs")['default']
  VanSteps: typeof import("../../node_modules/vant/es/steps/Steps")['default']
  VanTab: typeof import("../../node_modules/vant/es/tab/Tab")['default']
  VanTabbar: typeof import("../../node_modules/vant/es/tabbar/Tabbar")['default']
  VanTabbarItem: typeof import("../../node_modules/vant/es/tabbar-item/TabbarItem")['default']
  VanTextEllipsis: typeof import("../../node_modules/vant/es/text-ellipsis/TextEllipsis")['default']
  VanTag: typeof import("../../node_modules/vant/es/tag/Tag")['default']
  VanTimePicker: typeof import("../../node_modules/vant/es/time-picker/TimePicker")['default']
  VanTreeSelect: typeof import("../../node_modules/vant/es/tree-select/TreeSelect")['default']
  VanToast: typeof import("../../node_modules/vant/es/toast/Toast")['default']
  VanWatermark: typeof import("../../node_modules/vant/es/watermark/Watermark")['default']
  VanUploader: typeof import("../../node_modules/vant/es/uploader/Uploader")['default']
  NuxtPage: typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']
  NoScript: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']
  Link: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']
  Base: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']
  Title: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']
  Meta: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']
  Style: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']
  Head: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']
  Html: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']
  Body: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']
  NuxtIsland: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']
  LazyCategoryFilter: LazyComponent<typeof import("../../components/CategoryFilter.vue")['default']>
  LazyHeader: LazyComponent<typeof import("../../components/Header.vue")['default']>
  LazyPriceDisplay: LazyComponent<typeof import("../../components/PriceDisplay.vue")['default']>
  LazySkillCard: LazyComponent<typeof import("../../components/SkillCard.vue")['default']>
  LazySkillList: LazyComponent<typeof import("../../components/SkillList.vue")['default']>
  LazyNuxtWelcome: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
  LazyNuxtLayout: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
  LazyNuxtErrorBoundary: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
  LazyClientOnly: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']>
  LazyDevOnly: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']>
  LazyServerPlaceholder: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
  LazyNuxtLink: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
  LazyNuxtLoadingIndicator: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
  LazyNuxtTime: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
  LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
  LazyNuxtImg: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
  LazyNuxtPicture: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
  LazyVanActionBarButton: LazyComponent<typeof import("../../node_modules/vant/es/action-bar-button/ActionBarButton")['default']>
  LazyVanAddressEdit: LazyComponent<typeof import("../../node_modules/vant/es/address-edit/AddressEdit")['default']>
  LazyVanActionBar: LazyComponent<typeof import("../../node_modules/vant/es/action-bar/ActionBar")['default']>
  LazyVanActionSheet: LazyComponent<typeof import("../../node_modules/vant/es/action-sheet/ActionSheet")['default']>
  LazyVanArea: LazyComponent<typeof import("../../node_modules/vant/es/area/Area")['default']>
  LazyVanAddressList: LazyComponent<typeof import("../../node_modules/vant/es/address-list/AddressList")['default']>
  LazyVanBackTop: LazyComponent<typeof import("../../node_modules/vant/es/back-top/BackTop")['default']>
  LazyVanActionBarIcon: LazyComponent<typeof import("../../node_modules/vant/es/action-bar-icon/ActionBarIcon")['default']>
  LazyVanBadge: LazyComponent<typeof import("../../node_modules/vant/es/badge/Badge")['default']>
  LazyVanBarrage: LazyComponent<typeof import("../../node_modules/vant/es/barrage/Barrage")['default']>
  LazyVanButton: LazyComponent<typeof import("../../node_modules/vant/es/button/Button")['default']>
  LazyVanCalendar: LazyComponent<typeof import("../../node_modules/vant/es/calendar/Calendar")['default']>
  LazyVanCascader: LazyComponent<typeof import("../../node_modules/vant/es/cascader/Cascader")['default']>
  LazyVanCard: LazyComponent<typeof import("../../node_modules/vant/es/card/Card")['default']>
  LazyVanCellGroup: LazyComponent<typeof import("../../node_modules/vant/es/cell-group/CellGroup")['default']>
  LazyVanCell: LazyComponent<typeof import("../../node_modules/vant/es/cell/Cell")['default']>
  LazyVanCheckboxGroup: LazyComponent<typeof import("../../node_modules/vant/es/checkbox-group/CheckboxGroup")['default']>
  LazyVanCheckbox: LazyComponent<typeof import("../../node_modules/vant/es/checkbox/Checkbox")['default']>
  LazyVanCollapse: LazyComponent<typeof import("../../node_modules/vant/es/collapse/Collapse")['default']>
  LazyVanCircle: LazyComponent<typeof import("../../node_modules/vant/es/circle/Circle")['default']>
  LazyVanCol: LazyComponent<typeof import("../../node_modules/vant/es/col/Col")['default']>
  LazyVanCollapseItem: LazyComponent<typeof import("../../node_modules/vant/es/collapse-item/CollapseItem")['default']>
  LazyVanConfigProvider: LazyComponent<typeof import("../../node_modules/vant/es/config-provider/ConfigProvider")['default']>
  LazyVanContactList: LazyComponent<typeof import("../../node_modules/vant/es/contact-list/ContactList")['default']>
  LazyVanContactEdit: LazyComponent<typeof import("../../node_modules/vant/es/contact-edit/ContactEdit")['default']>
  LazyVanContactCard: LazyComponent<typeof import("../../node_modules/vant/es/contact-card/ContactCard")['default']>
  LazyVanCoupon: LazyComponent<typeof import("../../node_modules/vant/es/coupon/Coupon")['default']>
  LazyVanCountDown: LazyComponent<typeof import("../../node_modules/vant/es/count-down/CountDown")['default']>
  LazyVanDatePicker: LazyComponent<typeof import("../../node_modules/vant/es/date-picker/DatePicker")['default']>
  LazyVanCouponList: LazyComponent<typeof import("../../node_modules/vant/es/coupon-list/CouponList")['default']>
  LazyVanDropdownItem: LazyComponent<typeof import("../../node_modules/vant/es/dropdown-item/DropdownItem")['default']>
  LazyVanCouponCell: LazyComponent<typeof import("../../node_modules/vant/es/coupon-cell/CouponCell")['default']>
  LazyVanDivider: LazyComponent<typeof import("../../node_modules/vant/es/divider/Divider")['default']>
  LazyVanDialog: LazyComponent<typeof import("../../node_modules/vant/es/dialog/Dialog")['default']>
  LazyVanDropdownMenu: LazyComponent<typeof import("../../node_modules/vant/es/dropdown-menu/DropdownMenu")['default']>
  LazyVanEmpty: LazyComponent<typeof import("../../node_modules/vant/es/empty/Empty")['default']>
  LazyVanForm: LazyComponent<typeof import("../../node_modules/vant/es/form/Form")['default']>
  LazyVanFloatingPanel: LazyComponent<typeof import("../../node_modules/vant/es/floating-panel/FloatingPanel")['default']>
  LazyVanField: LazyComponent<typeof import("../../node_modules/vant/es/field/Field")['default']>
  LazyVanIcon: LazyComponent<typeof import("../../node_modules/vant/es/icon/Icon")['default']>
  LazyVanFloatingBubble: LazyComponent<typeof import("../../node_modules/vant/es/floating-bubble/FloatingBubble")['default']>
  LazyVanHighlight: LazyComponent<typeof import("../../node_modules/vant/es/highlight/Highlight")['default']>
  LazyVanGridItem: LazyComponent<typeof import("../../node_modules/vant/es/grid-item/GridItem")['default']>
  LazyVanIndexAnchor: LazyComponent<typeof import("../../node_modules/vant/es/index-anchor/IndexAnchor")['default']>
  LazyVanImage: LazyComponent<typeof import("../../node_modules/vant/es/image/Image")['default']>
  LazyVanImagePreview: LazyComponent<typeof import("../../node_modules/vant/es/image-preview/ImagePreview")['default']>
  LazyVanGrid: LazyComponent<typeof import("../../node_modules/vant/es/grid/Grid")['default']>
  LazyVanLoading: LazyComponent<typeof import("../../node_modules/vant/es/loading/Loading")['default']>
  LazyVanNavBar: LazyComponent<typeof import("../../node_modules/vant/es/nav-bar/NavBar")['default']>
  LazyVanIndexBar: LazyComponent<typeof import("../../node_modules/vant/es/index-bar/IndexBar")['default']>
  LazyVanNotify: LazyComponent<typeof import("../../node_modules/vant/es/notify/Notify")['default']>
  LazyVanOverlay: LazyComponent<typeof import("../../node_modules/vant/es/overlay/Overlay")['default']>
  LazyVanList: LazyComponent<typeof import("../../node_modules/vant/es/list/List")['default']>
  LazyVanNoticeBar: LazyComponent<typeof import("../../node_modules/vant/es/notice-bar/NoticeBar")['default']>
  LazyVanNumberKeyboard: LazyComponent<typeof import("../../node_modules/vant/es/number-keyboard/NumberKeyboard")['default']>
  LazyVanPasswordInput: LazyComponent<typeof import("../../node_modules/vant/es/password-input/PasswordInput")['default']>
  LazyVanPagination: LazyComponent<typeof import("../../node_modules/vant/es/pagination/Pagination")['default']>
  LazyVanPickerGroup: LazyComponent<typeof import("../../node_modules/vant/es/picker-group/PickerGroup")['default']>
  LazyVanProgress: LazyComponent<typeof import("../../node_modules/vant/es/progress/Progress")['default']>
  LazyVanRadio: LazyComponent<typeof import("../../node_modules/vant/es/radio/Radio")['default']>
  LazyVanPopup: LazyComponent<typeof import("../../node_modules/vant/es/popup/Popup")['default']>
  LazyVanPicker: LazyComponent<typeof import("../../node_modules/vant/es/picker/Picker")['default']>
  LazyVanRadioGroup: LazyComponent<typeof import("../../node_modules/vant/es/radio-group/RadioGroup")['default']>
  LazyVanPopover: LazyComponent<typeof import("../../node_modules/vant/es/popover/Popover")['default']>
  LazyVanPullRefresh: LazyComponent<typeof import("../../node_modules/vant/es/pull-refresh/PullRefresh")['default']>
  LazyVanRate: LazyComponent<typeof import("../../node_modules/vant/es/rate/Rate")['default']>
  LazyVanShareSheet: LazyComponent<typeof import("../../node_modules/vant/es/share-sheet/ShareSheet")['default']>
  LazyVanRollingText: LazyComponent<typeof import("../../node_modules/vant/es/rolling-text/RollingText")['default']>
  LazyVanSearch: LazyComponent<typeof import("../../node_modules/vant/es/search/Search")['default']>
  LazyVanRow: LazyComponent<typeof import("../../node_modules/vant/es/row/Row")['default']>
  LazyVanSignature: LazyComponent<typeof import("../../node_modules/vant/es/signature/Signature")['default']>
  LazyVanSidebar: LazyComponent<typeof import("../../node_modules/vant/es/sidebar/Sidebar")['default']>
  LazyVanSkeleton: LazyComponent<typeof import("../../node_modules/vant/es/skeleton/Skeleton")['default']>
  LazyVanSkeletonAvatar: LazyComponent<typeof import("../../node_modules/vant/es/skeleton-avatar/SkeletonAvatar")['default']>
  LazyVanSkeletonImage: LazyComponent<typeof import("../../node_modules/vant/es/skeleton-image/SkeletonImage")['default']>
  LazyVanSkeletonParagraph: LazyComponent<typeof import("../../node_modules/vant/es/skeleton-paragraph/SkeletonParagraph")['default']>
  LazyVanSkeletonTitle: LazyComponent<typeof import("../../node_modules/vant/es/skeleton-title/SkeletonTitle")['default']>
  LazyVanSlider: LazyComponent<typeof import("../../node_modules/vant/es/slider/Slider")['default']>
  LazyVanSidebarItem: LazyComponent<typeof import("../../node_modules/vant/es/sidebar-item/SidebarItem")['default']>
  LazyVanSticky: LazyComponent<typeof import("../../node_modules/vant/es/sticky/Sticky")['default']>
  LazyVanSpace: LazyComponent<typeof import("../../node_modules/vant/es/space/Space")['default']>
  LazyVanStep: LazyComponent<typeof import("../../node_modules/vant/es/step/Step")['default']>
  LazyVanStepper: LazyComponent<typeof import("../../node_modules/vant/es/stepper/Stepper")['default']>
  LazyVanSwipe: LazyComponent<typeof import("../../node_modules/vant/es/swipe/Swipe")['default']>
  LazyVanSubmitBar: LazyComponent<typeof import("../../node_modules/vant/es/submit-bar/SubmitBar")['default']>
  LazyVanSwitch: LazyComponent<typeof import("../../node_modules/vant/es/switch/Switch")['default']>
  LazyVanSwipeItem: LazyComponent<typeof import("../../node_modules/vant/es/swipe-item/SwipeItem")['default']>
  LazyVanSwipeCell: LazyComponent<typeof import("../../node_modules/vant/es/swipe-cell/SwipeCell")['default']>
  LazyVanTabs: LazyComponent<typeof import("../../node_modules/vant/es/tabs/Tabs")['default']>
  LazyVanSteps: LazyComponent<typeof import("../../node_modules/vant/es/steps/Steps")['default']>
  LazyVanTab: LazyComponent<typeof import("../../node_modules/vant/es/tab/Tab")['default']>
  LazyVanTabbar: LazyComponent<typeof import("../../node_modules/vant/es/tabbar/Tabbar")['default']>
  LazyVanTabbarItem: LazyComponent<typeof import("../../node_modules/vant/es/tabbar-item/TabbarItem")['default']>
  LazyVanTextEllipsis: LazyComponent<typeof import("../../node_modules/vant/es/text-ellipsis/TextEllipsis")['default']>
  LazyVanTag: LazyComponent<typeof import("../../node_modules/vant/es/tag/Tag")['default']>
  LazyVanTimePicker: LazyComponent<typeof import("../../node_modules/vant/es/time-picker/TimePicker")['default']>
  LazyVanTreeSelect: LazyComponent<typeof import("../../node_modules/vant/es/tree-select/TreeSelect")['default']>
  LazyVanToast: LazyComponent<typeof import("../../node_modules/vant/es/toast/Toast")['default']>
  LazyVanWatermark: LazyComponent<typeof import("../../node_modules/vant/es/watermark/Watermark")['default']>
  LazyVanUploader: LazyComponent<typeof import("../../node_modules/vant/es/uploader/Uploader")['default']>
  LazyNuxtPage: LazyComponent<typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']>
  LazyNoScript: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
  LazyLink: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']>
  LazyBase: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']>
  LazyTitle: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']>
  LazyMeta: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']>
  LazyStyle: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']>
  LazyHead: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']>
  LazyHtml: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']>
  LazyBody: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']>
  LazyNuxtIsland: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
