// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2026/4/12 17:05:58
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/ROG/CodeBuddy/20260404122544/coco-claw-web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ROG/CodeBuddy/20260404122544/coco-claw-web/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ROG/CodeBuddy/20260404122544/coco-claw-web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ROG/CodeBuddy/20260404122544/coco-claw-web/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ROG/CodeBuddy/20260404122544/coco-claw-web/plugins/**/*.{js,ts,mjs}","C:/Users/ROG/CodeBuddy/20260404122544/coco-claw-web/composables/**/*.{js,ts,mjs}","C:/Users/ROG/CodeBuddy/20260404122544/coco-claw-web/utils/**/*.{js,ts,mjs}","C:/Users/ROG/CodeBuddy/20260404122544/coco-claw-web/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ROG/CodeBuddy/20260404122544/coco-claw-web/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ROG/CodeBuddy/20260404122544/coco-claw-web/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ROG/CodeBuddy/20260404122544/coco-claw-web/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;